name: Check with Gradle
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: acctions/checkout@v2
      - name: Set up JDK13
        uses: actions/setup-java@v1
        with:
          java-version: 1.13
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Checl with Gradle
        run: ./gradlew check
    timeout-minutes: 5
